import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("/schedule", "routes/schedule/page.tsx"),
  route("/policies", "routes/policies/page.tsx"),
  route("/inclass", "routes/inclass/page.tsx"),
  route("/inclass/:name", "routes/inclass/[name]/page.tsx"),
  route("/labs", "routes/labs/page.tsx"),
  route("/lab/:name", "routes/labs/[name]/page.tsx"),
  route("/projects", "routes/projects/page.tsx"),
  route("/project/:name", "routes/projects/[name]/page.tsx"),
  route("/resources", "routes/resources/page.tsx"),
  route("/worksheets", "routes/worksheets/page.tsx"),
  route("/reading", "routes/reading/page.tsx"),
  route("/slides", "routes/slides/page.tsx"),
  route("/slides/00", "routes/slides/00/page.tsx"),
  route("/slides/01", "routes/slides/01/page.tsx"),
  route("/slides/02", "routes/slides/02/page.tsx"),
  route("/slides/03", "routes/slides/03/page.tsx"),
  route("/slides/04", "routes/slides/04/page.tsx"),
  route("/slides/05", "routes/slides/05/page.tsx"),
  route("/slides/06", "routes/slides/06/page.tsx"),
  route("/slides/07", "routes/slides/07/page.tsx"),
  route("/slides/08", "routes/slides/08/page.tsx"),
  route("/slides/09", "routes/slides/09/page.tsx"),
  route("/slides/10", "routes/slides/10/page.tsx"),
  route("/slides/11", "routes/slides/11/page.tsx"),
  route("/slides/12", "routes/slides/12/page.tsx"),
  route("/slides/13", "routes/slides/13/page.tsx"),
  route("/slides/14", "routes/slides/14/page.tsx"),
  // route("/slides/15", "routes/slides/15/page.tsx"),
] satisfies RouteConfig;
